`NumPy` (Numerical Python) adalah **library Python** yang digunakan untuk **komputasi numerik dan ilmiah**, terutama untuk:

* **Operasi array dan matriks** secara efisien.
* **Perhitungan matematika vektor dan matriks** (misalnya penjumlahan, perkalian, transpos, determinan, inverse, dll).
* **Manipulasi data dalam bentuk array multidimensi (n-dimensional array)**.
* **Fungsi-fungsi statistik, aljabar linear, transformasi Fourier, dan lainnya.**

---

### Contoh sederhana:

```python
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)  # [5 7 9]
```

### Kelebihan NumPy:

* Sangat **cepat** karena ditulis dalam C.
* **Memory-efficient** dibanding list Python biasa.
* Menjadi **dasar** dari banyak library lain seperti Pandas, SciPy, scikit-learn, TensorFlow, dan lainnya.

---

### Contoh penggunaan lain:

```python
# Matriks 2x2
mat = np.array([[1, 2], [3, 4]])

# Transpose
print(mat.T)

# Perkalian matriks
mat2 = np.array([[5, 6], [7, 8]])
print(np.dot(mat, mat2))
```

Kalau kamu tertarik dengan data science, machine learning, atau analisis data — **NumPy itu fondasi utama** yang wajib dikuasai. Mau dibantu belajar dasar-dasarnya?


In [2]:
import numpy as np 

In [3]:
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [4]:
arr[2]

3

In [6]:
a = np.array([[1,2], [3, 4]])
print(a)

[[1 2]
 [3 4]]


numpy.array(object, dtype=None, copy=True, order=None, subok=False, ndmin=0)

- object : Objek apa pun yang mengekspos metode antarmuka array mengembalikan array, atau apa pun (bersarang) urutan
- dtype  : type data, opsional
- copy   : Opsional. Secara default (True), objek disalin
- order  : C (baris mayor) atau F (utama kolom) atau A (apa saja) (default)
- subok  : Secara default, array yang dikembalikan dipaksa menjadi array kelas dasar. Jika benar, sub-kelas akan diberikan
- ndimin : Menentukan dimensi minimum dari array yang dihasilkan

# Tipe Data di Numpy

Di NumPy, tipe data disebut **`dtype` (data type)\`**, dan ini penting karena NumPy dirancang untuk bekerja dengan **array yang homogen**, artinya semua elemen dalam array memiliki tipe data yang sama.

Berikut jenis-jenis tipe data (`dtype`) utama di NumPy:

---

### 📊 **1. Tipe Numerik**

#### a. Integer (bilangan bulat)

| Tipe     | Ukuran          | Keterangan         |
| -------- | --------------- | ------------------ |
| `int8`   | 8-bit signed    | -128 to 127        |
| `int16`  | 16-bit signed   | -32,768 to 32,767  |
| `int32`  | 32-bit signed   | -2^31 to 2^31 - 1  |
| `int64`  | 64-bit signed   | -2^63 to 2^63 - 1  |
| `uint8`  | 8-bit unsigned  | 0 to 255           |
| `uint16` | 16-bit unsigned | 0 to 65,535        |
| `uint32` | 32-bit unsigned | 0 to 4,294,967,295 |
| `uint64` | 64-bit unsigned | 0 to 2^64 - 1      |

#### b. Float (bilangan desimal)

| Tipe      | Ukuran       | Keterangan               |
| --------- | ------------ | ------------------------ |
| `float16` | 16-bit float | Presisi rendah           |
| `float32` | 32-bit float | Presisi sedang (default) |
| `float64` | 64-bit float | Presisi tinggi           |

---

### 🔢 **2. Tipe Kompleks**

Digunakan untuk bilangan kompleks: `a + bj`

* `complex64`  → Real dan imaginary: 2 × 32-bit float
* `complex128` → Real dan imaginary: 2 × 64-bit float

---

### 🔤 **3. Tipe String**

* `str_`  → Unicode string (panjang tetap)
* `bytes_` → Byte string

Contoh:

```python
np.array(["halo", "dunia"], dtype=np.str_)
```

---

### 📅 **4. Tipe Waktu dan Tanggal**

* `datetime64` → Representasi waktu (misalnya `'2025-07-04'`)
* `timedelta64` → Durasi atau selisih waktu

---

### ✅ **5. Boolean**

* `bool_` → Hanya `True` atau `False`

---

### 🧬 **6. Object**

* `object_` → Untuk menyimpan objek Python bebas (misalnya campur string & angka)

```python
np.array([1, 'hello', True], dtype=object)
```

---

### 🔍 Melihat tipe data suatu array

```python
arr = np.array([1, 2, 3])
print(arr.dtype)  # int64 (tergantung sistem)

arr2 = np.array([1.0, 2.0])
print(arr2.dtype)  # float64
```

---

Kalau kamu mau, aku bisa bantu buatkan tabel ringkasan dalam format gambar juga. Mau?


In [7]:
print(a.dtype)

int64


In [8]:
# contoh 2 tipe data dengan unicode string
arr_1 = np.array(['rambutan', 'apel', 'jeruk'])
print(arr_1.dtype)
arr_1 = np.array(['r', 'a', 'j'])
print(arr_1.dtype)

<U8
<U1


In [9]:
#contoh 3 tipe data yang didefinisikan
arr_2 = np.array([1, 2, 3, 4], dtype='S')

print(arr_2)
print(arr_2.dtype)

[b'1' b'2' b'3' b'4']
|S1


👍 Bagus, kamu menemukan salah satu tipe string **khusus** di NumPy, yaitu **`dtype='S'`**.

---

### 🔤 `dtype='S'` artinya:

Tipe data **byte string** alias **string dalam bentuk bytes**, bukan Unicode.
Disimpan dalam format `bytes`, mirip seperti `b'hello'` di Python.

---

### 🧪 Contoh:

```python
import numpy as np

arr_2 = np.array([1, 2, 3, 4], dtype='S')
print(arr_2)         # [b'1' b'2' b'3' b'4']
print(arr_2.dtype)   # |S1
```

Penjelasan `|S1`:

* `S` → string bytes
* `1` → maksimal 1 byte per elemen (karena angka 1–9 cuma 1 karakter)
* `|` → byte-order (tidak penting untuk string)

---

### ⚠️ Ciri-ciri `S` (byte string):

* Isinya berupa `b'string'`, bukan `'string'` biasa.
* **Bukan Unicode**, jadi tidak bisa langsung menyimpan karakter non-ASCII seperti `'é'`, `'あ'`, atau `'😊'`.
* Lebih ringan dan cepat untuk teks ASCII sederhana.

---

### 💡 Perbandingan:

```python
# Unicode string
arr_unicode = np.array(['hello'], dtype='U')
print(arr_unicode)   # ['hello']
print(arr_unicode.dtype)  # <U5

# Byte string
arr_bytes = np.array(['hello'], dtype='S')
print(arr_bytes)     # [b'hello']
print(arr_bytes.dtype)  # |S5
```

---

### 🧠 Kapan pakai `'S'`?

* Saat kamu **hanya butuh teks ASCII biasa** dan ingin **hemat memori**.
* Tapi kalau kamu perlu dukungan karakter Unicode (misal `'你好'`, `'😊'`), **pakailah `'U'` atau `str`**.

---

Kalau kamu tertarik, bisa aku tunjukin juga contoh error saat karakter Unicode dimasukkan ke array `dtype='S'`. Mau?


In [10]:
#contoh 4 tipe data yang diubah
arrs = np.array([1.1, 2.1, 3.1])

newarr = arrs.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


# Membuat array dari yang sudah ada 

In [ ]:
x = [1, 2, 3, 4, 5]
print(type(x))
# ini bisa bikin array yang sudah di init
x = np.asarray(x)
print(x.dtype)
print(x)

<class 'list'>
int64
[1 2 3 4 5]


In [13]:
x = [1, 2, 3, 4, 5]
print(type(x))
x = np.asarray(x, dtype="f")
print(x.dtype)
print(x)

<class 'list'>
float32
[1. 2. 3. 4. 5.]


In [17]:
a = (1, 2, 3, 4, 5)
b = (6, 7, 8, 9, 10)

ab = [a, b]
print(ab)

ab_array_np = np.asarray(ab)
print(ab_array_np)

[(1, 2, 3, 4, 5), (6, 7, 8, 9, 10)]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
