`NumPy` (Numerical Python) adalah **library Python** yang digunakan untuk **komputasi numerik dan ilmiah**, terutama untuk:

* **Operasi array dan matriks** secara efisien.
* **Perhitungan matematika vektor dan matriks** (misalnya penjumlahan, perkalian, transpos, determinan, inverse, dll).
* **Manipulasi data dalam bentuk array multidimensi (n-dimensional array)**.
* **Fungsi-fungsi statistik, aljabar linear, transformasi Fourier, dan lainnya.**

---

### Contoh sederhana:

```python
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)  # [5 7 9]
```

### Kelebihan NumPy:

* Sangat **cepat** karena ditulis dalam C.
* **Memory-efficient** dibanding list Python biasa.
* Menjadi **dasar** dari banyak library lain seperti Pandas, SciPy, scikit-learn, TensorFlow, dan lainnya.

---

### Contoh penggunaan lain:

```python
# Matriks 2x2
mat = np.array([[1, 2], [3, 4]])

# Transpose
print(mat.T)

# Perkalian matriks
mat2 = np.array([[5, 6], [7, 8]])
print(np.dot(mat, mat2))
```
# anjay


In [1]:
import numpy as np 

print(np.__version__)

1.26.4


In [2]:
arr = np.array([1,2,3,4,5])# test
print(arr)

[1 2 3 4 5]


In [3]:
arr10: np.ndarray = np.array([1,2,3,4,5])
print(arr10)

[1 2 3 4 5]


In [4]:
arr[2]

3

In [5]:
a = np.array([[1,2], [3, 4]])
print(a)

[[1 2]
 [3 4]]


numpy.array(object, dtype=None, copy=True, order=None, subok=False, ndmin=0)

- object : Objek apa pun yang mengekspos metode antarmuka array mengembalikan array, atau apa pun (bersarang) urutan
- dtype  : type data, opsional
- copy   : Opsional. Secara default (True), objek disalin
- order  : C (baris mayor) atau F (utama kolom) atau A (apa saja) (default)
- subok  : Secara default, array yang dikembalikan dipaksa menjadi array kelas dasar. Jika benar, sub-kelas akan diberikan
- ndimin : Menentukan dimensi minimum dari array yang dihasilkan

# Tipe Data di Numpy

Di NumPy, tipe data disebut **`dtype` (data type)\`**, dan ini penting karena NumPy dirancang untuk bekerja dengan **array yang homogen**, artinya semua elemen dalam array memiliki tipe data yang sama.

Berikut jenis-jenis tipe data (`dtype`) utama di NumPy:

---

### 📊 **1. Tipe Numerik**

#### a. Integer (bilangan bulat)

| Tipe     | Ukuran          | Keterangan         |
| -------- | --------------- | ------------------ |
| `int8`   | 8-bit signed    | -128 to 127        |
| `int16`  | 16-bit signed   | -32,768 to 32,767  |
| `int32`  | 32-bit signed   | -2^31 to 2^31 - 1  |
| `int64`  | 64-bit signed   | -2^63 to 2^63 - 1  |
| `uint8`  | 8-bit unsigned  | 0 to 255           |
| `uint16` | 16-bit unsigned | 0 to 65,535        |
| `uint32` | 32-bit unsigned | 0 to 4,294,967,295 |
| `uint64` | 64-bit unsigned | 0 to 2^64 - 1      |

#### b. Float (bilangan desimal)

| Tipe      | Ukuran       | Keterangan               |
| --------- | ------------ | ------------------------ |
| `float16` | 16-bit float | Presisi rendah           |
| `float32` | 32-bit float | Presisi sedang (default) |
| `float64` | 64-bit float | Presisi tinggi           |

---

### 🔢 **2. Tipe Kompleks**

Digunakan untuk bilangan kompleks: `a + bj`

* `complex64`  → Real dan imaginary: 2 × 32-bit float
* `complex128` → Real dan imaginary: 2 × 64-bit float

---

### 🔤 **3. Tipe String**

* `str_`  → Unicode string (panjang tetap)
* `bytes_` → Byte string

Contoh:

```python
np.array(["halo", "dunia"], dtype=np.str_)
```

---

### 📅 **4. Tipe Waktu dan Tanggal**

* `datetime64` → Representasi waktu (misalnya `'2025-07-04'`)
* `timedelta64` → Durasi atau selisih waktu

---

### ✅ **5. Boolean**

* `bool_` → Hanya `True` atau `False`

---

### 🧬 **6. Object**

* `object_` → Untuk menyimpan objek Python bebas (misalnya campur string & angka)

```python
np.array([1, 'hello', True], dtype=object)
```

---

### 🔍 Melihat tipe data suatu array

```python
arr = np.array([1, 2, 3])
print(arr.dtype)  # int64 (tergantung sistem)

arr2 = np.array([1.0, 2.0])
print(arr2.dtype)  # float64
```

---

Kalau kamu mau, aku bisa bantu buatkan tabel ringkasan dalam format gambar juga. Mau?


In [6]:
print(a.dtype)

int64


In [7]:
# contoh 2 tipe data dengan unicode string
arr_1 = np.array(['rambutan', 'apel', 'jeruk'])
print(arr_1.dtype)
arr_1 = np.array(['r', 'a', 'j'])
print(arr_1.dtype)

<U8
<U1


In [8]:
#contoh 3 tipe data yang didefinisikan
arr_2 = np.array([1, 2, 3, 4], dtype='S')

print(arr_2)
print(arr_2.dtype)

[b'1' b'2' b'3' b'4']
|S1


👍 Bagus, kamu menemukan salah satu tipe string **khusus** di NumPy, yaitu **`dtype='S'`**.

---

### 🔤 `dtype='S'` artinya:

Tipe data **byte string** alias **string dalam bentuk bytes**, bukan Unicode.
Disimpan dalam format `bytes`, mirip seperti `b'hello'` di Python.

---

### 🧪 Contoh:

```python
import numpy as np

arr_2 = np.array([1, 2, 3, 4], dtype='S')
print(arr_2)         # [b'1' b'2' b'3' b'4']
print(arr_2.dtype)   # |S1
```

Penjelasan `|S1`:

* `S` → string bytes
* `1` → maksimal 1 byte per elemen (karena angka 1–9 cuma 1 karakter)
* `|` → byte-order (tidak penting untuk string)

---

### ⚠️ Ciri-ciri `S` (byte string):

* Isinya berupa `b'string'`, bukan `'string'` biasa.
* **Bukan Unicode**, jadi tidak bisa langsung menyimpan karakter non-ASCII seperti `'é'`, `'あ'`, atau `'😊'`.
* Lebih ringan dan cepat untuk teks ASCII sederhana.

---

### 💡 Perbandingan:

```python
# Unicode string
arr_unicode = np.array(['hello'], dtype='U')
print(arr_unicode)   # ['hello']
print(arr_unicode.dtype)  # <U5

# Byte string
arr_bytes = np.array(['hello'], dtype='S')
print(arr_bytes)     # [b'hello']
print(arr_bytes.dtype)  # |S5
```

---

### 🧠 Kapan pakai `'S'`?

* Saat kamu **hanya butuh teks ASCII biasa** dan ingin **hemat memori**.
* Tapi kalau kamu perlu dukungan karakter Unicode (misal `'你好'`, `'😊'`), **pakailah `'U'` atau `str`**.

---

Kalau kamu tertarik, bisa aku tunjukin juga contoh error saat karakter Unicode dimasukkan ke array `dtype='S'`. Mau?


In [9]:
#contoh 4 tipe data yang diubah
arrs = np.array([1.1, 2.1, 3.1])

print(arrs.dtype)

newarr = arrs.astype('i')

print(newarr)
print(newarr.dtype)

float64
[1 2 3]
int32


# Membuat array dari yang sudah ada 

In [10]:
x = [1, 2, 3, 4, 5]
print(type(x))
# ini bisa bikin array yang sudah di init
x = np.asarray(x)
print(x.dtype)
print(x)

<class 'list'>
int64
[1 2 3 4 5]


In [11]:
x = [1, 2, 3, 4, 5]
print(type(x))
x = np.asarray(x, dtype="f")
print(x.dtype)
print(x)

<class 'list'>
float32
[1. 2. 3. 4. 5.]


In [12]:
x = ["123", "456", "789"]
print(type(x))
x = np.asarray(x, dtype=int)
print(x.dtype)
print(x)


<class 'list'>
int64
[123 456 789]


In [13]:
a = (1, 2, 3, 4, 5)
b = (6, 7, 8, 9, 10)

ab = [a, b]
print(ab)

ab_array_np = np.asarray(ab)
print(ab_array_np)

[(1, 2, 3, 4, 5), (6, 7, 8, 9, 10)]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


Membuat rentang nilai menggunakan numpy (STUDY CASE) :
membuat dataframe menggunakan rentang nilai random dan deterministik



numpy.arange(start, stop, step, dtype)

`np.arange()` adalah fungsi di NumPy untuk membuat **array berisi deretan angka** dengan pola tertentu (mirip `range()` bawaan Python, tapi hasilnya array NumPy).

---

### 🔧 **Sintaks:**

```python
np.arange(start, stop, step, dtype=None)
```

* `start` → awal angka (default: 0)
* `stop` → batas akhir (tidak termasuk)
* `step` → loncatan antar angka (default: 1)
* `dtype` → tipe data (opsional)

---

### ✅ **Contoh Penggunaan:**

```python
import numpy as np

a = np.arange(0, 10)
print(a)  # [0 1 2 3 4 5 6 7 8 9]
```

```python
b = np.arange(1, 11, 2)
print(b)  # [1 3 5 7 9]
```

```python
c = np.arange(5, 0, -1)
print(c)  # [5 4 3 2 1]
```

---

### ⚠️ Kenapa pakai `np.arange` bukan `range`?

* `range()` menghasilkan objek Python biasa, **bukan NumPy array**.
* `np.arange()` lebih fleksibel dan bisa langsung digunakan untuk operasi matematis di NumPy.

---

### 🧠 Contoh lanjut:

```python
arr = np.arange(1, 6)
print(arr * 2)  # [ 2  4  6  8 10]
```

---

### 🔍 Perhatian:

Untuk data **floating point**, hasil `np.arange` bisa kurang presisi. Lebih aman pakai `np.linspace()` kalau kamu ingin titik-titik yang dibagi rata.

Contoh:

```python
np.arange(0, 1, 0.1)  # Bisa muncul angka aneh karena pembulatan float
np.linspace(0, 1, 10)  # Lebih akurat
```

---

Mau aku tunjukin juga visualisasi `np.arange()` atau bedanya dengan `linspace()` secara grafik?


In [14]:
z = np.arange(0, 1, 0.1, dtype=float)
x = np.arange(1, 11, 1)
y = np.arange(10, 20, 1)

In [15]:
print(z)
print(x)
print(y)

print(len(z), len(x), len(y))

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
[ 1  2  3  4  5  6  7  8  9 10]
[10 11 12 13 14 15 16 17 18 19]
10 10 10


In [16]:
c = np.arange(1, 12, lambda x: x**2, dtype=float)
print(c)

TypeError: unsupported operand type(s) for /: 'int' and 'function'

In [ ]:
import pandas as pd

In [ ]:
pd.DataFrame({'z' : z, 'x' : x, 'y' : y})

z   x   y
0  0.0   1  10
1  0.1   2  11
2  0.2   3  12
3  0.3   4  13
4  0.4   5  14
5  0.5   6  15
6  0.6   7  16
7  0.7   8  17
8  0.8   9  18
9  0.9  10  19

In [ ]:
#membuat array dengan nilai 1 di numpy
x = np.ones((3,4), dtype=int)
print(x)
print(x.dtype)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
int64


In [ ]:
#membuat array dengan nilai 0 di numpy
x = np.zeros((5,7))
print(x)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
x = np.full((3,4), 0.72)
print(x)

[[0.72 0.72 0.72 0.72]
 [0.72 0.72 0.72 0.72]
 [0.72 0.72 0.72 0.72]]


In [ ]:
x = np.random.rand(5,3)
print(x)

[[0.79834209 0.48582416 0.1194396 ]
 [0.6267462  0.74218488 0.13971669]
 [0.50097092 0.98515121 0.49411502]
 [0.07278296 0.0909067  0.77005527]
 [0.98475753 0.27009715 0.1199588 ]]


In [ ]:
pd.DataFrame(x, columns=['x', 'y', 'z'])

x         y         z
0  0.798342  0.485824  0.119440
1  0.626746  0.742185  0.139717
2  0.500971  0.985151  0.494115
3  0.072783  0.090907  0.770055
4  0.984758  0.270097  0.119959

# Tugas 1

In [ ]:
u = np.random.rand(3, 4)

df = pd.DataFrame(u, columns=['x', 'y', 'z', 'w'])
print(df)

          x         y         z         w
0  0.313421  0.476997  0.757567  0.994505
1  0.064052  0.337914  0.563423  0.337099
2  0.817936  0.849557  0.333137  0.049115


# Tugas 2

In [ ]:
satu = np.full((5, 6), 1)
nol = np.full((5, 6), 0)

#

df_satu = pd.DataFrame(satu)
df_nol = pd.DataFrame(nol)

gabung = pd.concat([df_satu, df_nol], axis=1)
print(gabung)

   0  1  2  3  4  5  0  1  2  3  4  5
0  1  1  1  1  1  1  0  0  0  0  0  0
1  1  1  1  1  1  1  0  0  0  0  0  0
2  1  1  1  1  1  1  0  0  0  0  0  0
3  1  1  1  1  1  1  0  0  0  0  0  0
4  1  1  1  1  1  1  0  0  0  0  0  0
