In [2]:
import numpy as np

# Slicing dan Indexing

`# Slicing and Indexing` di NumPy berarti **mengambil sebagian data dari array**, baik satu elemen, beberapa elemen, satu baris, satu kolom, atau bagian-bagian tertentu.

🧠 Ini sangat penting karena NumPy dipakai untuk manipulasi data numerik dan array besar. Dengan **indexing dan slicing**, kamu bisa mengakses atau mengubah data secara efisien.

---

## 📌 1. **Indexing**: Mengakses elemen spesifik

```python
import numpy as np

arr = np.array([10, 20, 30, 40])

print(arr[0])  # 10 (elemen pertama)
print(arr[-1]) # 40 (elemen terakhir)
```

### Untuk array 2D:

```python
mat = np.array([[1, 2, 3],
                [4, 5, 6]])

print(mat[0, 1])  # 2 (baris 0, kolom 1)
print(mat[1, 2])  # 6 (baris 1, kolom 2)
```

---

## 📌 2. **Slicing**: Mengambil rentang elemen

### Satu dimensi:

```python
arr = np.array([10, 20, 30, 40, 50])

print(arr[1:4])  # [20 30 40]
print(arr[:3])   # [10 20 30]
print(arr[::2])  # [10 30 50] (loncatan 2)
```

### Dua dimensi (2D array):

```python
mat = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

print(mat[0:2, 1:])  # ambil baris 0-1, kolom 1-end
# [[2 3]
#  [5 6]]
```

---

## 📌 3. **Mengambil baris atau kolom tertentu**

```python
print(mat[1, :])   # baris ke-1: [4 5 6]
print(mat[:, 2])   # kolom ke-2: [3 6 9]
```

---

## 📌 4. **Boolean indexing**

```python
arr = np.array([10, 15, 20, 25])
print(arr[arr > 15])  # [20 25]
```

---

## 📌 5. **Fancy indexing (pakai array index)**

```python
arr = np.array([100, 200, 300, 400])
print(arr[[0, 3]])  # [100 400]
```

---

## 🎯 Kesimpulan

| Teknik          | Contoh               | Artinya          |
| --------------- | -------------------- | ---------------- |
| `arr[2]`        | Elemen ke-3          | Indexing         |
| `arr[1:4]`      | Elemen 1–3           | Slicing          |
| `mat[0, 2]`     | Baris 0, kolom 2     | Index 2D         |
| `mat[:, 0]`     | Semua baris, kolom 0 | Kolom pertama    |
| `arr[arr > 10]` | Elemen > 10          | Boolean indexing |
| `arr[[0, 2]]`   | Index ke-0 dan ke-2  | Fancy indexing   |

---

Mau aku buatin gambar visual dari slicing di array 2D biar makin gampang paham?


In [3]:
# contoh 1 index tunggal, field index
a = np.arange(10) 
print(a)
b = a[5] 
print(b)

[0 1 2 3 4 5 6 7 8 9]
5


In [4]:
# Contoh 2
a = np.arange(10) 
print(a)
s = slice(2,7,2) 
print(a[s])

[0 1 2 3 4 5 6 7 8 9]
[2 4 6]


In [5]:
#contoh 3
a = np.arange(10) 
b = a[2:7:2] 
print(b)

[2 4 6]


In [6]:
#contoh 4 slicing index hanya dengan menggunakan parameter start
a = np.arange(10) 
print(a)
print(a[2:])

[0 1 2 3 4 5 6 7 8 9]
[2 3 4 5 6 7 8 9]


In [7]:
#contoh 5 slicing menggunakan start dan stop index
a = np.arange(10) 
print(a)
print(a[2:5])

[0 1 2 3 4 5 6 7 8 9]
[2 3 4]


In [8]:
#contoh 6 slicing pada array dua dimensi
a = np.array([[1,2,3],[3,4,5],[4,5,6]]) 
print(a)

# slice items starting from index
print('slice array dari index a[1:]') 
print(a[1:])

[[1 2 3]
 [3 4 5]
 [4 5 6]]
slice array dari index a[1:]
[[3 4 5]
 [4 5 6]]


In [9]:
#contoh 7 menggunakan ellipsis (...)
a = np.array([[1,2,3],
              [3,4,5],
              [4,5,6]]) 

print('Array kita:') 
print(a) 
print('\n')  

# ini mengembalikan item di kolom kedua dari array utama 
print('item dari kolom kedua:')  
print(a[...,1]) 
print('\n')  

# slice semua item dari baris kedua 
print('Item dari baris kedua:') 
print(a[1,...]) 
print('\n')  

# kita akan slice item dari kolom 1 dan seterusnya
print('item dari kolom 1 dan seterusnya:') 
print(a[...,1:])


Array kita:
[[1 2 3]
 [3 4 5]
 [4 5 6]]


item dari kolom kedua:
[2 4 5]


Item dari baris kedua:
[3 4 5]


item dari kolom 1 dan seterusnya:
[[2 3]
 [4 5]
 [5 6]]


Study Case 
1. Buat array 2 dimensi dengan shape=(3,4)
2. Index dengan mengambil item dari baris kedua dan seterusnya sampai bariss terakhir
3. Index dengan mengambil item dari kolom 1 dan 2

In [10]:
a = np.array([[1,2,3,7],
              [3,4,5,8],
              [4,5,6,9]])

slicing_1 = a[1:,...]
print(slicing_1)

slicing_2 = a[..., :2]
# print(slicing_2)

# numpy dua belum selesai
#mantap jiwa
# belom selesai juga bang

[[3 4 5 8]
 [4 5 6 9]]


## Advance Indexing

### Integer Indexing di NumPy

**Integer indexing** adalah teknik indexing (pengambilan elemen array) di NumPy dengan menggunakan **indeks bilangan bulat (integer)**, baik satu dimensi maupun banyak dimensi.

Kalau kamu sudah paham slicing (`a[1:3, :]`), maka integer indexing ini sedikit berbeda karena memungkinkan kita untuk **mengambil elemen secara bebas di posisi tertentu**, bukan range.

---

### Contoh Dasar

Misalnya kamu punya array 2 dimensi:

```python
import numpy as np

a = np.array([[10, 20, 30],
              [40, 50, 60],
              [70, 80, 90]])
```

#### 1. Mengambil elemen spesifik (dengan 1 indeks untuk setiap dimensi)

```python
# Ambil elemen baris ke-0 kolom ke-2
print(a[0, 2])  # Output: 30
```

#### 2. Integer indexing dalam bentuk array

```python
# Ambil elemen dari posisi (0,0), (1,1), (2,2)
baris = np.array([0, 1, 2])
kolom = np.array([0, 1, 2])
print(a[baris, kolom])  # Output: [10 50 90]
```

> Ini seperti mengambil **diagonal utama** dari matriks.

---

### Integer Indexing vs Slicing

```python
# Slicing: ambil seluruh baris pertama
print(a[0, :])  # [10 20 30]

# Integer indexing: ambil elemen di kolom 0, 1, 2 tapi hanya dari baris 0
print(a[0, [0, 1, 2]])  # [10 20 30]

# Integer indexing: ambil (0,1), (1,1), (2,1)
print(a[[0,1,2], 1])  # [20 50 80]
```

---

### Gunanya integer indexing?

* Mengakses elemen spesifik secara fleksibel
* Berguna untuk mengambil subset berdasarkan kondisi/logika lain
* Digabung dengan boolean indexing untuk filtering lanjutan

---

Kalau kamu mau contoh study case-nya juga (misalnya untuk klasifikasi, pengolahan data, dll), tinggal bilang aja ya!


In [11]:
#contoh 1 mengakses element dari array dua dimensi dengan menentukan baris dan kolom yang disalin
x = np.array([[1, 2], 
              [3, 4], 
              [5, 6]]) 
y = x[[0,1,2], [0,1,0]] 
print(y)

[1 4 5]


In [ ]:
#contoh 2 mengakses element dari array dua dimensi dengan menentukan baris dan kolom yang disalin
x = np.array([[ 0,  1,  2],
              [ 3,  4,  5],
              [ 6,  7,  8],
              [ 9, 10, 11]]) 
   
print('array asli:') 
print(x) 
print('\n') 

rows = np.array([[0,0],[3,3]]) #Baris pertama dan keempat
cols = np.array([[0,2],[0,2]]) #Kolom pertama dan ketiga
y = x[rows,cols] 
   
print('Hasil dari index integer:') 
print(y)