In [1]:
import numpy as np
# mencoba numpy yang kedua

# Slicing dan Indexing

`# Slicing and Indexing` di NumPy berarti **mengambil sebagian data dari array**, baik satu elemen, beberapa elemen, satu baris, satu kolom, atau bagian-bagian tertentu.

🧠 Ini sangat penting karena NumPy dipakai untuk manipulasi data numerik dan array besar. Dengan **indexing dan slicing**, kamu bisa mengakses atau mengubah data secara efisien.

---

## 📌 1. **Indexing**: Mengakses elemen spesifik

```python
import numpy as np

arr = np.array([10, 20, 30, 40])

print(arr[0])  # 10 (elemen pertama)
print(arr[-1]) # 40 (elemen terakhir)
```

### Untuk array 2D:

```python
mat = np.array([[1, 2, 3],
                [4, 5, 6]])

print(mat[0, 1])  # 2 (baris 0, kolom 1)
print(mat[1, 2])  # 6 (baris 1, kolom 2)
```

---

## 📌 2. **Slicing**: Mengambil rentang elemen

### Satu dimensi:

```python
arr = np.array([10, 20, 30, 40, 50])

print(arr[1:4])  # [20 30 40]
print(arr[:3])   # [10 20 30]
print(arr[::2])  # [10 30 50] (loncatan 2)
```

### Dua dimensi (2D array):

```python
mat = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

print(mat[0:2, 1:])  # ambil baris 0-1, kolom 1-end
# [[2 3]
#  [5 6]]
```

---

## 📌 3. **Mengambil baris atau kolom tertentu**

```python
print(mat[1, :])   # baris ke-1: [4 5 6]
print(mat[:, 2])   # kolom ke-2: [3 6 9]
```

---

## 📌 4. **Boolean indexing**

```python
arr = np.array([10, 15, 20, 25])
print(arr[arr > 15])  # [20 25]
```

---

## 📌 5. **Fancy indexing (pakai array index)**

```python
arr = np.array([100, 200, 300, 400])
print(arr[[0, 3]])  # [100 400]
```

---

## 🎯 Kesimpulan

| Teknik          | Contoh               | Artinya          |
| --------------- | -------------------- | ---------------- |
| `arr[2]`        | Elemen ke-3          | Indexing         |
| `arr[1:4]`      | Elemen 1–3           | Slicing          |
| `mat[0, 2]`     | Baris 0, kolom 2     | Index 2D         |
| `mat[:, 0]`     | Semua baris, kolom 0 | Kolom pertama    |
| `arr[arr > 10]` | Elemen > 10          | Boolean indexing |
| `arr[[0, 2]]`   | Index ke-0 dan ke-2  | Fancy indexing   |

---

Mau aku buatin gambar visual dari slicing di array 2D biar makin gampang paham?


In [2]:
# contoh 1 index tunggal, field index
a = np.arange(10) 
print(a)
b = a[5] 
print(b)

[0 1 2 3 4 5 6 7 8 9]
5


In [3]:
# Contoh 2
a = np.arange(10) 
print(a)
s = slice(2,7,2) 
print(a[s])

[0 1 2 3 4 5 6 7 8 9]
[2 4 6]


In [4]:
#contoh 3
a = np.arange(10)
# a[start:stop:step]
b = a[2:7:2] 
print(b)

[2 4 6]


In [5]:
#contoh 4 slicing index hanya dengan menggunakan parameter start
a = np.arange(10) 
print(a)
# ini ngambil index ke dua sampai akhir
print(a[2:])

[0 1 2 3 4 5 6 7 8 9]
[2 3 4 5 6 7 8 9]


In [6]:
#contoh 5 slicing menggunakan start dan stop index
a = np.arange(10) 
print(a)
# ini ngambil rentang index kedua sampai ke lima, tapi ke lima kagak di ambil
print(a[2:5])

[0 1 2 3 4 5 6 7 8 9]
[2 3 4]


In [7]:
#contoh 6 slicing pada array dua dimensi
a = np.array([[1,2,3],[3,4,5],[4,5,6]]) 
print(a)

# slice items starting from index
print('slice array dari index a[1:]')
# kalau array nya berbentuk 2 dimensi atau table atau matriks
# a[baris:kolom]
print(a[1:])

[[1 2 3]
 [3 4 5]
 [4 5 6]]
slice array dari index a[1:]
[[3 4 5]
 [4 5 6]]


In [8]:
#contoh 7 menggunakan ellipsis (...)
a = np.array([[1,2,3],
              [3,4,5],
              [4,5,6]]) 

print('Array kita:') 
print(a) 
print('\n')  

# ini mengembalikan item di kolom kedua dari array utama 
print('item dari kolom kedua:')
# mengambil baris atau kolom bisa di abaikan
# kek a[..., 1] gitu
# bisa sebalik nya a[1, ...]
# ini untuk ngambil kolom
print(a[...,1]) 
print('\n')  

# slice semua item dari baris kedua 
print('Item dari baris kedua:') 
# ini untuk ngambil baris
print(a[1,...]) 
print('\n')  

# kita akan slice item dari kolom 1 dan seterusnya
print('item dari kolom 1 dan seterusnya:')
# ini ngabil kolom/atau baris bisa pakai metode 1 dims/vektor 
# pake a[start:stop:step]
# jadi bisa gini a[start:stop:step, start:stop:step]
print(a[...,1:])

print("ambil nilai 4")
print(a[1, 1])


Array kita:
[[1 2 3]
 [3 4 5]
 [4 5 6]]


item dari kolom kedua:
[2 4 5]


Item dari baris kedua:
[3 4 5]


item dari kolom 1 dan seterusnya:
[[2 3]
 [4 5]
 [5 6]]
ambil nilai 4
4


Study Case

1. Buat array 2 dimensi dengan shape=(3,4)
2. Index dengan mengambil item dari baris kedua dan seterusnya sampai bariss terakhir
3. Index dengan mengambil item dari kolom 1 dan 2


In [9]:
a = np.array([[1,2,3,7],
              [3,4,5,8],
              [4,5,6,9]])

slicing_1 = a[1:,...]
print(slicing_1)

slicing_2 = a[..., :2]
# print(slicing_2)

# numpy dua belum selesai
#mantap jiwa
# belom selesai juga bang
# checkpoint sampai sini 

[[3 4 5 8]
 [4 5 6 9]]


## Advance Indexing


### Integer Indexing di NumPy

**Integer indexing** adalah teknik indexing (pengambilan elemen array) di NumPy dengan menggunakan **indeks bilangan bulat (integer)**, baik satu dimensi maupun banyak dimensi.

Kalau kamu sudah paham slicing (`a[1:3, :]`), maka integer indexing ini sedikit berbeda karena memungkinkan kita untuk **mengambil elemen secara bebas di posisi tertentu**, bukan range.

---

### Contoh Dasar

Misalnya kamu punya array 2 dimensi:

```python
import numpy as np

a = np.array([[10, 20, 30],
              [40, 50, 60],
              [70, 80, 90]])
```

#### 1. Mengambil elemen spesifik (dengan 1 indeks untuk setiap dimensi)

```python
# Ambil elemen baris ke-0 kolom ke-2
print(a[0, 2])  # Output: 30
```

#### 2. Integer indexing dalam bentuk array

```python
# Ambil elemen dari posisi (0,0), (1,1), (2,2)
baris = np.array([0, 1, 2])
kolom = np.array([0, 1, 2])
print(a[baris, kolom])  # Output: [10 50 90]
```

> Ini seperti mengambil **diagonal utama** dari matriks.

---

### Integer Indexing vs Slicing

```python
# Slicing: ambil seluruh baris pertama
print(a[0, :])  # [10 20 30]

# Integer indexing: ambil elemen di kolom 0, 1, 2 tapi hanya dari baris 0
print(a[0, [0, 1, 2]])  # [10 20 30]

# Integer indexing: ambil (0,1), (1,1), (2,1)
print(a[[0,1,2], 1])  # [20 50 80]
```

---

### Gunanya integer indexing?

- Mengakses elemen spesifik secara fleksibel
- Berguna untuk mengambil subset berdasarkan kondisi/logika lain
- Digabung dengan boolean indexing untuk filtering lanjutan

---

Kalau kamu mau contoh study case-nya juga (misalnya untuk klasifikasi, pengolahan data, dll), tinggal bilang aja ya!


In [10]:
#contoh 1 mengakses element dari array dua dimensi dengan menentukan baris dan kolom yang disalin
x = np.array([[1, 2], 
              [3, 4], 
              [5, 6]]) 
y = x[[0,1,2], [0,1,0]] 
print(y)

[1 4 5]


In [11]:
#contoh 2 mengakses element dari array dua dimensi dengan menentukan baris dan kolom yang disalin
x = np.array([[ 0,  1,  2],
              [ 3,  4,  5],
              [ 6,  7,  8],
              [ 9, 10, 11]]) 
   
print('array asli:') 
print(x) 
print('\n') 

rows = np.array([[0,0],[3,3]]) #Baris pertama dan keempat
cols = np.array([[0,2],[0,2]]) #Kolom pertama dan ketiga
y = x[rows,cols] 
   
print('Hasil dari index integer:') 
print(y)

array asli:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


Hasil dari index integer:
[[ 0  2]
 [ 9 11]]


In [12]:
#contoh 3
x = np.array([[ 0,  1,  2],
              [ 3,  4,  5],
              [ 6,  7,  8],
              [ 9, 10, 11]]) 

print('Array asli:')
print(x) 
print('\n')  

# slicing 
z = x[1:4,1:3] 

print('setelah, hasil array menjadi:') 
print(z) 
print('\n')  

# using advanced index for column 
y = x[1:4,[1,2]] 

print('slicing dengan advance index untuk column:') 
print(y)

# susah bjir ini numpy

Array asli:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


setelah, hasil array menjadi:
[[ 4  5]
 [ 7  8]
 [10 11]]


slicing dengan advance index untuk column:
[[ 4  5]
 [ 7  8]
 [10 11]]


# Bolean indexing 

In [13]:
x = np.array([[ 0,  1,  2],
              [ 3,  4,  5],
              [ 6,  7,  8],
              [ 9, 10, 11]]) 

print("array asli :")
print(x)
print("\n")

# ngambil item di atas angaka lima
print("item yang lebih besar dari lima :")
print(x[x > 5])

array asli :
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


item yang lebih besar dari lima :
[ 6  7  8  9 10 11]


In [14]:
#contoh 2
# ngambil item yang nan doang
a = np.array([np.nan, 1,2,np.nan,3,4,5]) 
print(a[np.isnan(a)])

[nan nan]


In [ ]:
#contoh 3
# ngambil item yang bukan bilang komples
# `~` untuk negasi
a = np.array([1, 2+6j, 5, 3.5+5j]) 
print(a[~np.iscomplex(a)])

[1.+0.j 5.+0.j]


Study Case 
1. Buat array 2 dimensi dengan shape=(3,4) yang
  isinya campuran antara complex, nan dan integer
2. Ambil item dengan menggunakan index boolean khusus integer, nan dan complex

In [30]:
a = np.array([
    [1,      np.nan, 3+2j,   4],
    [5,      6,       np.nan, 7+0j],
    [8+1j,   9,       10,     np.nan]
])

print(a[(a > 0) & (~np.iscomplex(a))])
print(a[np.isnan(a)])
print(a[np.iscomplex(a)])

[ 1.+0.j  4.+0.j  5.+0.j  6.+0.j  7.+0.j  9.+0.j 10.+0.j]
[nan+0.j nan+0.j nan+0.j]
[3.+2.j 8.+1.j]


/tmp/ipykernel_21750/2017132615.py:7: RuntimeWarning: invalid value encountered in greater
  print(a[(a > 0) & (~np.iscomplex(a))])


# Array Manipulation

## Reshape

In [ ]:
a = np.arange(8)
print('Array asli:')
print(a)
print('\n')

# ngerubah jadi 4 kali 2, ada 4 baris 2 kolom
b = a.reshape(4,2)
print('Array yang telah di modifikasi:')
print(b)


Array asli:
[0 1 2 3 4 5 6 7]


Array yang telah di modifikasi:
[[0 1]
 [2 3]
 [4 5]
 [6 7]]


# Perbedaan Flatten ama Ravel, Copy vs View

Perbedaan utama antara `ravel()` dan `flatten()` di NumPy adalah pada **cara mereka menangani memori (copy vs view)**.

---

### ✅ **1. `flatten()`**

* **Selalu mengembalikan salinan baru (copy)** dari array asli.
* Perubahan pada array hasil `flatten()` **tidak memengaruhi** array asal.
* Berlaku untuk semua array, apapun bentuknya (contiguous maupun tidak).

```python
a = np.array([[1, 2], [3, 4]])
b = a.flatten()
b[0] = 100

print(a)  # [[1 2]
          #  [3 4]] -> tidak berubah
print(b)  # [100 2 3 4] -> berubah sendiri
```

---

### ✅ **2. `ravel()`**

* **Mengembalikan view (bukan salinan)** jika memungkinkan.
* Jadi, perubahan pada hasil `ravel()` bisa **mengubah array asal**, *asalkan masih contiguous* di memori.
* Kalau tidak bisa view, maka akan tetap bikin salinan (mirip `flatten()`).

```python
a = np.array([[1, 2], [3, 4]])
b = a.ravel()
b[0] = 100

print(a)  # [[100   2]
          #  [  3   4]] -> berubah!
print(b)  # [100 2 3 4]
```

---

### 🧠 Ringkasan:

| Fitur            | `ravel()`                 | `flatten()`               |
| ---------------- | ------------------------- | ------------------------- |
| Return           | View jika bisa, else copy | Selalu copy               |
| Memory efficient | ✅ Lebih hemat             | ❌ Tidak selalu hemat      |
| Mutable effect   | Bisa ubah array asal      | Tidak mengubah array asal |
| Kecepatan        | Biasanya lebih cepat      | Sedikit lebih lambat      |

---

### 🧪 Gunakan Kapan?

* Pakai `ravel()` kalau kamu **tidak butuh salinan** dan ingin **efisiensi**.
* Pakai `flatten()` kalau kamu **ingin pastikan hasilnya terpisah dari array asli**.

Mau aku tunjukin juga kapan `ravel()` jadi copy, bukan view?


## Flatten

In [32]:
a = np.arange(8).reshape(2,4) #take copy

print('Array asli:')
print(a) 
print('\n')  


print('Array yang telah di flattened:') 
print(a.flatten()) 
print('\n')  

print('flattened array dalam F-style ordering:')
print(a.flatten(order = 'F'))

Array asli:
[[0 1 2 3]
 [4 5 6 7]]


Array yang telah di flattened:
[0 1 2 3 4 5 6 7]


flattened array dalam F-style ordering:
[0 4 1 5 2 6 3 7]


### Ravel

In [33]:
a = np.arange(8).reshape(2,4) # only view

print('Array asli:') 
print(a) 
print('\n')  

print('hasil dari fungsi ravel:') 
print(a.ravel())  
print('\n') 

print('menggunakan ravel function dalam F-style ordering:')
print(a.ravel(order = 'F'))

Array asli:
[[0 1 2 3]
 [4 5 6 7]]


hasil dari fungsi ravel:
[0 1 2 3 4 5 6 7]


menggunakan ravel function dalam F-style ordering:
[0 4 1 5 2 6 3 7]


## Operasi Transpos

In [35]:
a = np.arange(12).reshape(3,4)

# merubah dari bari ke kolom dan kolom jadi baris/ di puter se arah jarum jam

print('Array asli:') 
print(a)  
print('\n') 

print('Array yang telah di transpos:') 
print(np.transpose(a)) #parameter dengan list int, sesuai dengan dimensi. Secara default, dimensi dibalik
print('\n') 

print('Array yang telah di transpos dengan .T:') 
print(a.T)

Array asli:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


Array yang telah di transpos:
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


Array yang telah di transpos dengan .T:
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


## Penggabungan array

### concatenate

In [ ]:
a = np.array([[1,2],[3,4]]) 

print('Array Pertama:')
print(a) 
print('\n')  
b = np.array([[5,6],[7,8]]) 

print('Array Kedua:') 
print(b) 
print('\n')  
# both the arrays are of same dimensions 

# 0 itu vertikal
# 1 itu horizontal
print('gabungan dua array di sumbu 0:') 
print(np.concatenate((a,b)) )
print('\n') 

print('gabungan dua array di sumbu 1:') 
print(np.concatenate((a,b),axis = 1))

Array Pertama:
[[1 2]
 [3 4]]


Array Kedua:
[[5 6]
 [7 8]]


gabungan dua array di sumbu 0:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


gabungan dua array di sumbu 1:
[[1 2 5 6]
 [3 4 7 8]]


### stack

In [38]:
a = np.array([[1,2],[3,4]]) 

print('Array Pertama:') 
print(a) 
print('\n')


b = np.array([[5,6],[7,8]]) 

print('Array kedua:') 
print(b) 
print('\n')  

print('Stack dua array pada sumbu 0:') 
print(np.stack((a,b),0) )
print('\n')  

print('Stack dua array pada sumbu 1:') 
print(np.stack((a,b),1))

Array Pertama:
[[1 2]
 [3 4]]


Array kedua:
[[5 6]
 [7 8]]


Stack dua array pada sumbu 0:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


Stack dua array pada sumbu 1:
[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


### hstack
kiri kanan

In [39]:
a = np.array([[1,2],[3,4]]) 

print('Array Pertama:') 
print(a) 
print('\n')  
b = np.array([[5,6],[7,8]]) 

print('Array Kedua:') 
print(b) 
print('\n')  

print('Horizontal stacking:') 
c = np.hstack((a,b)) 
print(c) 
print('\n')



Array Pertama:
[[1 2]
 [3 4]]


Array Kedua:
[[5 6]
 [7 8]]


Horizontal stacking:
[[1 2 5 6]
 [3 4 7 8]]




### vstack

In [40]:
a = np.array([[1,2],[3,4]]) 

print('Array pertama:') 
print(a) 
print('\n')  
b = np.array([[5,6],[7,8]]) 

print('Array kedua:') 
print(b) 
print('\n')

print('Vertical stacking:') 
c = np.vstack((a,b)) 
print(c)


Array pertama:
[[1 2]
 [3 4]]


Array kedua:
[[5 6]
 [7 8]]


Vertical stacking:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


## Splitting Array (Pemisahan Array) menjadi sub-array

### split

In [43]:
a = np.arange(9)  

print('Array pertama:') 
print(a) 
print('\n')  

print('split array menjadi 3 sub-array yang setara:') 
b = np.split(a,3) 
print(b) 
print('\n')  

print('split berdasarkan index pada array 1 dimensi:') 
b = np.split(a,[4,5]) # numpy.split(ary, indices_or_sections, axis) 
# parameter indicec_or_section dapat berupa bilangan bulat, 
#yang menunjukkan jumlah subarray berukuran sama yang akan dibuat dari array input.
print(b)


Array pertama:
[0 1 2 3 4 5 6 7 8]


split array menjadi 3 sub-array yang setara:
[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]


split berdasarkan index pada array 1 dimensi:
[array([0, 1, 2, 3]), array([4]), array([5, 6, 7, 8])]
